# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: rtk-ai.rtk
PackageVersion: 0.51.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rtk.exe
  PortableCommandAlias: rtk
ReleaseDate: 2026-10-02
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/rtk-ai/rtk/releases/download/v0.51.0/rtk-x86_64-pc-windows-msvc.zip
  InstallerSha256: 1623E9B45D28B15122D69E7314776E1123A804224885CE07E7182FB40080F05C
ManifestType: installer
ManifestVersion: 1.12.0
